language: python

services:
  - docker

stages:
  - test
  - build

before_install:
  - pip install yq ansible

jobs:
  include:
    - script: cd apps/chat_broadcast_sse && ./bin/build.sh
      stage: build
